site_name: GPT-RAG
site_description: Official project documentation
site_author: Paulo Lacerda
repo_url: https://github.com/azure/gpt-rag
theme:
  name: material
  custom_dir: overrides
  language: en
  logo: media/logo.png
  favicon: favicon.ico
  palette:
    scheme: default
  features:
    - content.icon
    - content.iconify
    - navigation.tracking
    - toc.integrate
    - content.code.annotate
    - navigation.top
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - What's New: whatisnew.md
  - Deployment Guide: deploy.md
  - Quick Start Guides:
    - Simple RAG: quickstart_simple_rag.md
    - NL2SQL: quickstart_nl2sql.md
  - Architecture:
    - Overview: architecture.md
  - Services:
    - Orchestrator: services_orchestrator.md
    - Ingestion:
        - Overview: services_ingestion.md
        - Blob: ingestion_blob_data_source.md
        - Sharepoint: ingestion_sharepoint_source.md
        - NL2SQL: ingestion_nl2sql_data_source.md
  - How-to Guides:
    - User Feedback: howto_userfeedback.md
    - Sharepoint Connector: howto_sharepoint_connector.md
  - Meet the Team: team.md
  - Contributing: contributing.md    
extra:
  generator: false
extra_css:
  - styles.css